version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u242-jdk

    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "pom.xml" }}
      - run:
          name: Perform Build
          command: mvn -T 1C clean install
      - persist_to_workspace:
          root: target
          paths:
            - payments-0.0.1-SNAPSHOT.jar

  deploy:
    docker:
      - image: circleci/buildpack-deps:stable-curl
    working_directory: ~/work
    steps:
      - attach_workspace:
          at: ~/work
      - add_ssh_keys:
          fingerprints:
            - "$DEPLOY_FINGERPRINT"
      - run:
          name: Upload WAR file
          command: |
            ls
            pwd
            ls *
            scp payments-0.0.1-SNAPSHOT.jar "${DEPLOY_SERVER}"
            ls

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
