version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u242-jdk

    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "pom.xml" }}
      - run:
          name: Perform Build
          command: mvn -T 1C clean install
